ARG BASE_TAG=latest
FROM maciekleks/l7egg-base:$BASE_TAG as base

RUN make all DEBUG=0 LIBBPF_DIR=/usr

FROM gcr.io/distroless/base

WORKDIR /l7egg/build
COPY --from=base /l7egg/build/l7egg-k8s-static /l7egg/build/l7egg.bpf.o ./

ENTRYPOINT ["./l7egg-k8s-static"]