Vagrant.configure(2) do |config|
  config.vm.box = "minimal/xenial64"
  config.vm.synced_folder ".", "/vagrant", disabled: true

  config.vm.define :node2 do |node|
    node.vm.network :private_network, ip: "192.168.57.12"
    node.vm.provision :shell, inline: <<-SHELL
      ip link add vxlan5 type vxlan id 5 dstport 4789
      ip addr add 192.168.5.2/24 dev vxlan5
      ip link set up vxlan5
      bridge fdb add 00:00:00:00:00:00 dev vxlan5 dst 192.168.57.13
    SHELL
  end

  config.vm.define :node3 do |node|
    node.vm.network :private_network, ip: "192.168.57.13"
    node.vm.provision :shell, inline: <<-SHELL
      ip link add vxlan5 type vxlan id 5 dstport 4789
      ip addr add 192.168.5.3/24 dev vxlan5
      ip link set up vxlan5
      bridge fdb add 00:00:00:00:00:00 dev vxlan5 dst 192.168.67.12
    SHELL
  end
end
