apiVersion: apps/v1
kind: Deployment
metadata:
  name: tester
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tester
  template:
    metadata:
      labels:
        app: tester
    spec:
      #https://stackoverflow.com/questions/43486828/how-to-make-host-interfaces-including-cni-accessible-in-kubernetes-privileged
      #hostNetwork: true
      containers:
      - name: tester
        #image: git.d00b.pl:5050/spartakus/tools/builder
        image: maciekleks/kseg:0.1.24
        command: [ "/bin/sleep", "3650d" ]
        imagePullPolicy: Always
        securityContext:
          privileged: true #change to CAP_NET_ADMIN and CAP_NET_RAW tty: true
      imagePullSecrets:
      - name: regcred
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - ubu-ebpf3
