apiVersion: maciekleks.dev/v1alpha1
kind: ClusterEgg
metadata:
  name: clusteregg-example-tc
spec:
  programType: tc
  ingress:
    interfaceName: enp0s3
  egress:
    interfaceName: enp0s3
    commonNames:
    - www.onet.pl
    - .ubuntu.com
    - bbc.com
    cidrs:
    - cidr: 172.172.34.3/32
      ports:
      - port: 443
        protocol: TCP
    - cidr: 10.0.0.0/24
      ports:
      - port: 80
        protocol: TCP
    - cidr: 2a04:4e42:200::81/128
      ports:
      - port: 22
        protocol: TCP
    #shaping:
    #  rate: 1mbit
    #  ceil: 1mbit
