apiVersion: maciekleks.dev/v1alpha1
kind: ClusterEgg
metadata:
  name: clusteregg-pod-example
spec:
  ingress: {}
  egress:
    shaping:
      rate: 2mbps
    commonNames:
    - www.onet.pl
    - www.interia.pl
    - cluster.local
    cidrs:
    - 10.152.183.0/24
    - 169.254.1.1/32
    - 192.168.57.0/24
    podSelector:
      matchLabels:
        app: tester