name: Build with Makefile

on: [push]

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: |
        echo "deb http://cz.archive.ubuntu.com/ubuntu noble main" | sudo tee -a /etc/apt/sources.list
        sudo apt update
        sudo apt install -y libbpf-dev=1:1.3.0-2
        dpkg -s libbpf-dev | grep Version
        dpkg -L libbpf-dev #check the libbpf-dev package contents

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.20.x
    - name: Check out code
      uses: actions/checkout@v2
      with:
        fetch-depth: 0
        submodules: recursive
    - name: Check kernel version
      run: uname -r
    - name: Get dependencies
      run: go get -v -t -d ./...
    - name: Run Makefile
      run: DEBUG=0 GO=/usr/bin/go LIBBPF_DIR=/usr/lib/x86_64-linux-gnu make dynamic-with-libbpf-dev
    - name: build directory listing
      run: ls -l build